security:
    encoders:
        App\Entity\Client:
            algorithm: bcrypt
    providers:
        user_provider:
            entity:
                class: App\Entity\Client
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

    access_control:
