version: "3.6"

services:
    # Core configuration
    php:
        container_name: ${CONTAINER_NAME}_php
        build:
            context: .
            target: base
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
            BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
        ports:
            - '${PHP_PORT}:9000'
        depends_on:
          - mysql
        volumes:
            - './:${WORKPATH}:rw,cached'
            - './docker/php/php.ini:/usr/local/etc/php/php.ini'
        restart: always

    nginx:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx:${NGINX_VERSION}-alpine
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - php
        volumes:
            - './:${WORKPATH}:ro'
            - './docker/nginx/conf.d/core/nginx.conf:/etc/nginx/nginx.conf'
            - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
            - './docker/nginx/logs/:/var/log/nginx'
        restart: always

    # Server optimization
    redis:
        container_name: ${CONTAINER_NAME}_redis
        image: redis:${REDIS_VERSION}-alpine
        ports:
            - '${REDIS_PORT}:6379'
        depends_on:
            - php
        restart: always

    # DB configuration
    mysql:
        container_name: ${CONTAINER_NAME}_mysql
        image: mysql:${MYSQL_VERSION}
        ports:
            - '${MYSQL_PORT}:3306'
        environment:
            MYSQL_DATABASE: '${MYSQL_DBNAME}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        volumes:
            - 'mysql:/var/lib/mysql'
        restart: always

    # Performances configuration
    blackfire:
        container_name: ${CONTAINER_NAME}_blackfire
        image: blackfire/blackfire
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
            BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
            BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID}'
            BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN}'
        depends_on:
            - php
        volumes:
            - './:${WORKPATH}:rw,cached'
        restart: always

volumes:
    mysql:
