version: "3.6"

services:
    php:
        container_name: ${CONTAINER_NAME}_php
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: base
        depends_on:
            - mysql            
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
        volumes:
            - ./:${WORKPATH}:rw,cached
        ports:
            - '${PHP_PORT}:9000'            
        restart: always

    nginx:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx:1.15.7-alpine
        depends_on:
            - php        
        volumes:
            - ./:${WORKPATH}:ro
            - ./docker/nginx/conf.d/core/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '${NGINX_PORT}:80'            
        restart: always

    mysql:
        container_name: ${CONTAINER_NAME}_mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${MYSQL_DBNAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - '${MYSQL_PORT}:3306'            
        restart: always

    blackfire:
        container_name: ${CONTAINER_NAME}_blackfire
        image: blackfire/blackfire
        depends_on:
            - php        
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
        volumes:
            - ./:${WORKPATH}:rw,cached
        restart: always

volumes:
    mysql: {}
