parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false  

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # custom extension to extend queries on user collections
    'App\Doctrine\CurrentClientExtension':
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
    
    # custom decorator to document token obtainment     
    'App\Swagger\TokenDecorator':
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@App\Swagger\TokenDecorator.inner' ]
        autoconfigure: false
        
    # custom decorator to document responses         
    'App\Swagger\ResponseDecorator':
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@App\Swagger\ResponseDecorator.inner' ]
        autoconfigure: false        
        
    # Collections search filter
    product.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { brand: 'exact' } ]
        tags:  [ 'api_platform.filter' ]      
        autowire: false
        autoconfigure: false
        public: false       
        
    user.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { lastname: 'exact', email: 'exact' } ]
        tags:  [ 'api_platform.filter' ]      
        autowire: false
        autoconfigure: false
        public: false
